Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -9,15 +9,21 @@ jobs:
         run: sudo apt-get update && sudo apt-get install -y build-essential wget cpio python3 unzip rsync bc libncurses-dev libelf-dev libssl-dev bison flex xorriso mtools libisoburn-dev gettext texinfo libwayland-dev libxkbcommon-dev libpixman-1-dev libgbm-dev
       - name: Debug and Verify Paths
         run: |
-          echo "--- DEBUG: Current Working Directory ---"
+          cd buildroot
+          echo "--- DEBUG: Current Path ---"
           pwd
           
-          echo "--- DEBUG: Root of Repository (../) ---"
-          ls -R ../
+          # Проверяем файлы, используя полный путь через GITHUB_WORKSPACE
+          # GITHUB_WORKSPACE = /home/runner/work/nano-linux/nano-linux/
+          POST_SCRIPT="${GITHUB_WORKSPACE}/post-build.sh"
+          OVERLAY_DIR="${GITHUB_WORKSPACE}/board/nano_linux/rootfs-overlay"
           
-          echo "--- DEBUG: Verifying specific files ---"
-          [ -f "../post-build.sh" ] && echo "OK: post-build.sh found" || echo "ERROR: post-build.sh MISSING"
-          [ -d "../board/nano_linux/rootfs-overlay" ] && echo "OK: rootfs-overlay found" || echo "ERROR: rootfs-overlay MISSING"
+          echo "Checking $POST_SCRIPT"
+          [ -f "$POST_SCRIPT" ] && echo "OK: post-build.sh found" || echo "ERROR: post-build.sh MISSING"
+          
+          echo "Checking $OVERLAY_DIR"
+          [ -d "$OVERLAY_DIR" ] && echo "OK: rootfs-overlay found" || echo "ERROR: rootfs-overlay MISSING"
+          
           
       - name: Build
         run: |
